-- Rollback-only behavioral regression for grouped supervisor replacement decisions.
-- Shapes one source entitlement as quantity two, then proves two exact one-unit remedies
-- are accepted atomically into two child-free same-order routes and one resolved