import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/utils/supabase/server";
import { generateVatDraftRunAction } from "./actions";

type Row = Record<string, unknown>;
type TabKey = "overview" | "runs" | "blockers" | "journals" | "source" | "sage";

type DataSet = { rows: Row[]; error: string | null; count: number };
type Col = { label: string; render: (row: Row) => string };

const money = new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", minimumFractionDigits: 2 });
const tabs: Array<{ key: TabKey; label: string; hint: string }> = [
  { key: "overview", label: "Overview", hint: "Control view" },
  { key: "runs", label: "VAT Runs", hint: "Return packs" },
  { key: "blockers", label: "Blockers", hint: "Stops/risks" },
  { key: "journals", label: "Journals", hint: "Adjustment queue" },
  { key: "source", label: "Source Facts", hint: "Invoice/funding" },
  { key: "sage", label: "Sage Coverage", hint: "Posted coverage" },
];

function s(v: unknown) { if (typeof v === "string") return v; if (typeof v === "number" && Number.isFinite(v)) return String(v); if (typeof v === "boolean") return v ? "true" : "false"; return ""; }
function n(v: unknown) { if (typeof v === "number" && Number.isFinite(v)) return v; if (typeof v === "string" && v.trim()) { const p = Number(v); return Number.isFinite(p) ? p : 0; } return 0; }
function gbp(v: unknown) { return money.format(n(v)); }
function pretty(v: unknown) { const raw = s(v).trim(); return raw ? raw.replaceAll("_", " ") : "—"; }
function cut(v: unknown, max = 36) { const raw = s(v).trim(); return raw ? (raw.length > max ? `${raw.slice(0, max - 1)}…` : raw) : "—"; }
function date(v: unknown) { const raw = s(v).trim(); if (!raw) return "—"; const d = new Date(raw); if (Number.isNaN(d.getTime())) return raw; return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(d); }
function tone(t: "ok" | "warn" | "block" | "info" | "muted") { if (t === "ok") return "border-emerald-200 bg-emerald-50 text-emerald-900"; if (t === "warn") return "border-amber-200 bg-amber-50 text-amber-900"; if (t === "block") return "border-rose-200 bg-rose-50 text-rose-900"; if (t === "info") return "border-sky-200 bg-sky-50 text-sky-900"; return "border-slate-200 bg-slate-50 text-slate-700"; }
function one(v: unknown) { return Array.isArray(v) ? s(v[0]) : s(v); }
function tabFrom(v: unknown): TabKey { const k = one(v) as TabKey; return tabs.some((tab) => tab.key === k) ? k : "overview"; }
function pageFrom(v: unknown) { const p = Number(one(v)); return Number.isFinite(p) && p > 0 ? Math.floor(p) : 1; }
function sizeFrom(v: unknown) { const p = Number(one(v)); return [10, 25, 50, 100].includes(p) ? p : 25; }
function href(active: TabKey, patch: Record<string, string | number | null | undefined>, current: Record<string, string>) { const p = new URLSearchParams(current); p.set("tab", active); Object.entries(patch).forEach(([k, v]) => { if (v === null || v === undefined || v === "") p.delete(k); else p.set(k, String(v)); }); return `/internal/accounting-vat?${p.toString()}`; }

function Card({ label, value, detail, state = "muted" }: { label: string; value: string; detail: string; state?: "ok" | "warn" | "block" | "info" | "muted" }) { return <div className={`rounded-2xl border p-4 shadow-sm ${tone(state)}`}><p className="text-[11px] font-bold uppercase tracking-wide opacity-70">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p><p className="mt-2 text-xs leading-5 opacity-90">{detail}</p></div>; }
function Step({ no, title, detail, active = false }: { no: string; title: string; detail: string; active?: boolean }) { return <div className={`rounded-2xl border p-4 ${active ? tone("info") : tone("muted")}`}><div className="flex items-center gap-2"><span className="inline-flex h-8 min-w-8 items-center justify-center rounded-full bg-white px-2 text-xs font-extrabold ring-1 ring-slate-200">{no}</span><h3 className="font-semibold">{title}</h3></div><p className="mt-2 text-xs leading-5 opacity-90">{detail}</p></div>; }
function Tabs({ active, current }: { active: TabKey; current: Record<string, string> }) { return <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map((tab) => <Link key={tab.key} href={href(tab.key, { page: 1 }, current)} className={`min-w-fit rounded-2xl border px-4 py-3 text-sm ${tab.key === active ? "border-sky-300 bg-sky-50 text-sky-900" : "border-slate-200 bg-white text-slate-600 hover:bg-slate-50"}`}><span className="block font-bold">{tab.label}</span><span className="mt-1 block text-xs opacity-75">{tab.hint}</span></Link>)}</div></section>; }

function FilterBar({ active, current, q, status, severity, pageSize }: { active: TabKey; current: Record<string, string>; q: string; status: string; severity: string; pageSize: number }) {
  return <form method="get" action="/internal/accounting-vat" className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><input type="hidden" name="tab" value={active} /><input type="hidden" name="page" value="1" /><div className="grid gap-3 md:grid-cols-5"><label className="md:col-span-2 text-xs font-bold uppercase tracking-wide text-slate-500">Search<input name="q" defaultValue={q} placeholder="Ref, status, code, source..." className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium normal-case tracking-normal text-slate-900" /></label><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Status<select name="status" defaultValue={status} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium normal-case tracking-normal text-slate-900"><option value="">All</option><option value="open">Open</option><option value="draft">Draft</option><option value="posted">Posted</option><option value="platform_calculated">Platform calculated</option><option value="admin_approved">Admin approved</option><option value="matched_to_sage_locked">Locked</option></select></label><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Severity<select name="severity" defaultValue={severity} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium normal-case tracking-normal text-slate-900"><option value="">All</option><option value="blocker">Blocker</option><option value="warning">Warning</option><option value="info">Info</option></select></label><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Rows<select name="pageSize" defaultValue={String(pageSize)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium normal-case tracking-normal text-slate-900"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></label></div><div className="mt-3 flex flex-wrap gap-2"><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Apply filters</button><Link href={href(active, { q: null, status: null, severity: null, page: 1, pageSize }, current)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">Clear</Link></div></form>;
}

function GenerateDraftRunPanel({ foundationReady }: { foundationReady: boolean }) {
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold tracking-tight">Generate draft VAT return pack</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Admin-only source-line snapshot. This creates a draft run and blockers only. It does not approve journals, post to Sage, submit to HMRC, or lock a return.</p></div>{!foundationReady ? <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Foundation migration required</span> : null}</div><form action={generateVatDraftRunAction} className="mt-4 grid gap-3 md:grid-cols-4"><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Period start<input required type="date" name="period_start_date" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium normal-case tracking-normal text-slate-900" /></label><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Period end<input required type="date" name="period_end_date" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium normal-case tracking-normal text-slate-900" /></label><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Label<input name="return_period_label" placeholder="Q2 2026" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium normal-case tracking-normal text-slate-900" /></label><div className="flex items-end"><button disabled={!foundationReady} className={`w-full rounded-xl px-4 py-2 text-sm font-semibold ${foundationReady ? "bg-slate-950 text-white" : "cursor-not-allowed bg-slate-200 text-slate-500"}`}>Generate draft pack</button></div></form></section>;
}

function Pager({ active, current, total, page, pageSize }: { active: TabKey; current: Record<string, string>; total: number; page: number; pageSize: number }) {
  const pages = Math.max(1, Math.ceil(total / pageSize)); const from = total === 0 ? 0 : (page - 1) * pageSize + 1; const to = Math.min(page * pageSize, total);
  return <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-3 text-sm text-slate-600"><span>Showing {from}-{to} of {total}</span><div className="flex gap-2"><Link aria-disabled={page <= 1} className={`rounded-xl border px-3 py-2 font-semibold ${page <= 1 ? "pointer-events-none border-slate-100 text-slate-300" : "border-slate-200 text-slate-700"}`} href={href(active, { page: Math.max(1, page - 1), pageSize }, current)}>Previous</Link><span className="rounded-xl bg-slate-100 px-3 py-2 font-semibold text-slate-700">Page {page} / {pages}</span><Link aria-disabled={page >= pages} className={`rounded-xl border px-3 py-2 font-semibold ${page >= pages ? "pointer-events-none border-slate-100 text-slate-300" : "border-slate-200 text-slate-700"}`} href={href(active, { page: Math.min(pages, page + 1), pageSize }, current)}>Next</Link></div></div>;
}

async function countRows(db: any, table: string, configure?: (q: any) => any) { let q = db.from(table).select("*", { count: "exact", head: true }); if (configure) q = configure(q); const { count, error } = await q; return { count: count ?? 0, error: error?.message ? String(error.message) : null }; }
async function listRows(db: any, table: string, cols: string, page: number, pageSize: number, configure?: (q: any) => any): Promise<DataSet> { let q = db.from(table).select(cols, { count: "exact" }); if (configure) q = configure(q); const from = (page - 1) * pageSize; const to = from + pageSize - 1; const { data, error, count } = await q.range(from, to); return { rows: (data ?? []) as Row[], error: error?.message ? String(error.message) : null, count: count ?? 0 }; }
function Table({ title, data, columns }: { title: string; data: DataSet; columns: Col[] }) { return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold tracking-tight">{title}</h2>{data.error ? <p className="mt-1 text-xs font-semibold text-rose-700">Read error: {data.error}</p> : null}</div><span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-bold text-slate-600">{data.rows.length} shown</span></div><div className="mt-4 overflow-x-auto"><table className="min-w-full divide-y divide-slate-200 text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map((c) => <th key={c.label} className="whitespace-nowrap px-3 py-2 font-bold">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{data.rows.length === 0 ? <tr><td className="px-3 py-5 text-sm text-slate-500" colSpan={columns.length}>No rows to show yet.</td></tr> : data.rows.map((row, i) => <tr key={`${title}-${i}`}>{columns.map((c) => <td key={c.label} className="whitespace-nowrap px-3 py-2 text-slate-700">{c.render(row)}</td>)}</tr>)}</tbody></table></div></section>; }

export default async function InternalAccountingVatPage({ searchParams }: any = {}) {
  const params = searchParams ? await searchParams : {}; const activeTab = tabFrom(params?.tab); const page = pageFrom(params?.page); const pageSize = sizeFrom(params?.pageSize); const q = one(params?.q).trim(); const status = one(params?.status).trim(); const severity = one(params?.severity).trim(); const vatError = one(params?.vatError).trim(); const vatGenerated = one(params?.vatGenerated).trim();
  const current: Record<string, string> = { tab: activeTab, page: String(page), pageSize: String(pageSize) }; if (q) current.q = q; if (status) current.status = status; if (severity) current.severity = severity;
  const supabase = await createClient(); const db = supabase as any; const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: staff } = await supabase.from("staff").select("id, full_name, role_type").eq("auth_user_id", user.id).eq("active", true).maybeSingle(); if (!staff) redirect("/auth/check");
  if (s((staff as Row).role_type) !== "admin") return <main className="min-h-screen bg-slate-50 px-6 py-8 text-slate-950"><div className="mx-auto max-w-4xl rounded-3xl border border-rose-200 bg-white p-6 shadow-sm"><Link href="/internal" className="text-sm font-semibold text-sky-600">← Back to internal dashboard</Link><p className="mt-6 text-sm font-medium uppercase tracking-[0.2em] text-rose-500">Admin-only VAT control</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">VAT Return Workbench</h1><p className="mt-3 text-sm leading-6 text-slate-600">Live VAT return controls are restricted to admin users.</p></div></main>;

  const [salesInvoices, draftSalesInvoices, postedSalesInvoices, fundingEvents, receiptSnapshots, postedReceiptSnapshots, customerSalesSnapshots, postedCustomerSalesSnapshots, vatReturnRuns, vatReturnRunLines, vatAdjustmentJournals, vatAdjustmentJournalLines, vatMatchEvidence, vatBlockers, openVatBlockers] = await Promise.all([
    countRows(db, "sales_invoices"), countRows(db, "sales_invoices", (x) => x.eq("sage_status", "draft")), countRows(db, "sales_invoices", (x) => x.eq("sage_status", "posted")), countRows(db, "order_funding_events"), countRows(db, "cash_posting_snapshots", (x) => x.eq("posting_category", "customer_receipt_on_account")), countRows(db, "cash_posting_snapshots", (x) => x.eq("posting_category", "customer_receipt_on_account").in("sage_posting_status", ["posted", "posted_needs_review"])), countRows(db, "sage_posting_snapshots", (x) => x.eq("document_lane", "customer_sales").eq("active", true)), countRows(db, "sage_posting_snapshots", (x) => x.eq("document_lane", "customer_sales").eq("active", true).eq("sage_posting_status", "posted")), countRows(db, "vat_return_runs"), countRows(db, "vat_return_run_lines"), countRows(db, "vat_return_adjustment_journals"), countRows(db, "vat_return_adjustment_journal_lines"), countRows(db, "vat_return_sage_match_evidence"), countRows(db, "vat_return_blockers"), countRows(db, "vat_return_blockers", (x) => x.eq("status", "open")),
  ]);

  const runFilter = (x: any) => { let r = x.order("created_at", { ascending: false }); if (status) r = r.eq("status", status); if (q) r = r.or(`run_ref.ilike.%${q}%,return_period_label.ilike.%${q}%,status.ilike.%${q}%`); return r; };
  const blockerFilter = (x: any) => { let r = x.order("created_at", { ascending: false }); if (status) r = r.eq("status", status); if (severity) r = r.eq("severity", severity); if (q) r = r.or(`blocker_code.ilike.%${q}%,source_table.ilike.%${q}%,source_ref.ilike.%${q}%,message.ilike.%${q}%,required_action.ilike.%${q}%`); return r; };
  const journalFilter = (x: any) => { let r = x.order("created_at", { ascending: false }); if (status) r = r.eq("status", status); if (q) r = r.or(`adjustment_type.ilike.%${q}%,direction.ilike.%${q}%,status.ilike.%${q}%,sage_journal_ref.ilike.%${q}%`); return r; };
  const invoiceFilter = (x: any) => { let r = x.order("created_at", { ascending: false }); if (status) r = r.eq("sage_status", status); if (q) r = r.or(`invoice_type.ilike.%${q}%,sage_status.ilike.%${q}%,zero_rating_status.ilike.%${q}%,sage_invoice_id.ilike.%${q}%`); return r; };
  const fundingFilter = (x: any) => { let r = x.order("created_at", { ascending: false }); if (q) r = r.or(`event_type.ilike.%${q}%,source_ref.ilike.%${q}%,source_entity_type.ilike.%${q}%`); return r; };
  const receiptFilter = (x: any) => { let r = x.eq("posting_category", "customer_receipt_on_account").order("created_at", { ascending: false }); if (status) r = r.eq("sage_posting_status", status); if (q) r = r.or(`order_ref.ilike.%${q}%,sage_posting_status.ilike.%${q}%,sage_payment_on_account_id.ilike.%${q}%`); return r; };
  const sageFilter = (x: any) => { let r = x.eq("document_lane", "customer_sales").eq("active", true).order("created_at", { ascending: false }); if (status) r = r.eq("sage_posting_status", status); if (q) r = r.or(`document_type.ilike.%${q}%,order_ref.ilike.%${q}%,sage_posting_status.ilike.%${q}%,sage_invoice_id.ilike.%${q}%`); return r; };

  const [runs, blockers, journals, invoices, funds, receipts, sageRows] = await Promise.all([
    listRows(db, "vat_return_runs", "id, run_ref, return_period_label, period_start_date, period_end_date, status, expected_box1_gbp, expected_box4_gbp, expected_box6_gbp, expected_box7_gbp, locked_at, created_at", page, pageSize, runFilter),
    listRows(db, "vat_return_blockers", "id, blocker_code, severity, status, source_table, source_ref, message, required_action, created_at", page, pageSize, blockerFilter),
    listRows(db, "vat_return_adjustment_journals", "id, adjustment_type, target_box, direction, amount_gbp, status, sage_journal_ref, posted_at, created_at", page, pageSize, journalFilter),
    listRows(db, "sales_invoices", "id, invoice_type, amount_gbp, sage_status, consideration_received_date, sage_invoice_date, zero_rating_deadline_date, zero_rating_status, sage_invoice_id, sage_posted_at, created_at", page, pageSize, invoiceFilter),
    listRows(db, "order_funding_events", "id, event_type, amount_gbp, source_ref, source_entity_type, created_at", page, pageSize, fundingFilter),
    listRows(db, "cash_posting_snapshots", "id, order_ref, amount_gbp, posting_date, sage_posting_status, sage_payment_on_account_id, created_at", page, pageSize, receiptFilter),
    listRows(db, "sage_posting_snapshots", "id, document_type, order_ref, amount_gbp, sage_posting_status, sage_invoice_id, sage_posted_at, created_at", page, pageSize, sageFilter),
  ]);

  const foundationReady = [vatReturnRuns, vatReturnRunLines, vatAdjustmentJournals, vatAdjustmentJournalLines, vatMatchEvidence, vatBlockers].every((i) => !i.error);
  const runCols: Col[] = [{ label: "Run", render: (r) => cut(r.run_ref) }, { label: "Period", render: (r) => cut(r.return_period_label) }, { label: "Start", render: (r) => date(r.period_start_date) }, { label: "End", render: (r) => date(r.period_end_date) }, { label: "Status", render: (r) => pretty(r.status) }, { label: "Box 1", render: (r) => gbp(r.expected_box1_gbp) }, { label: "Box 4", render: (r) => gbp(r.expected_box4_gbp) }, { label: "Box 6", render: (r) => gbp(r.expected_box6_gbp) }, { label: "Box 7", render: (r) => gbp(r.expected_box7_gbp) }];
  const blockerCols: Col[] = [{ label: "Severity", render: (r) => pretty(r.severity) }, { label: "Status", render: (r) => pretty(r.status) }, { label: "Code", render: (r) => cut(r.blocker_code, 42) }, { label: "Source", render: (r) => cut(r.source_table) }, { label: "Message", render: (r) => cut(r.message, 72) }, { label: "Required action", render: (r) => cut(r.required_action, 72) }];
  const journalCols: Col[] = [{ label: "Type", render: (r) => pretty(r.adjustment_type) }, { label: "Box", render: (r) => cut(r.target_box) }, { label: "Direction", render: (r) => pretty(r.direction) }, { label: "Amount", render: (r) => gbp(r.amount_gbp) }, { label: "Status", render: (r) => pretty(r.status) }, { label: "Sage ref", render: (r) => cut(r.sage_journal_ref) }, { label: "Posted", render: (r) => date(r.posted_at) }];
  const invoiceCols: Col[] = [{ label: "Type", render: (r) => pretty(r.invoice_type) }, { label: "Amount", render: (r) => gbp(r.amount_gbp) }, { label: "Sage", render: (r) => pretty(r.sage_status) }, { label: "Payment/tax point", render: (r) => date(r.consideration_received_date) }, { label: "Invoice date", render: (r) => date(r.sage_invoice_date) }, { label: "Evidence deadline", render: (r) => date(r.zero_rating_deadline_date) }, { label: "Zero-rate", render: (r) => pretty(r.zero_rating_status) }];
  const fundingCols: Col[] = [{ label: "Event", render: (r) => pretty(r.event_type) }, { label: "Amount", render: (r) => gbp(r.amount_gbp) }, { label: "Source", render: (r) => pretty(r.source_entity_type) }, { label: "Reference", render: (r) => cut(r.source_ref, 42) }, { label: "Created", render: (r) => date(r.created_at) }];
  const receiptCols: Col[] = [{ label: "Order", render: (r) => cut(r.order_ref) }, { label: "Amount", render: (r) => gbp(r.amount_gbp) }, { label: "Receipt date", render: (r) => date(r.posting_date) }, { label: "Sage receipt", render: (r) => pretty(r.sage_posting_status) }, { label: "POA id", render: (r) => cut(r.sage_payment_on_account_id) }];
  const sageCols: Col[] = [{ label: "Document", render: (r) => pretty(r.document_type) }, { label: "Order", render: (r) => cut(r.order_ref) }, { label: "Amount", render: (r) => gbp(r.amount_gbp) }, { label: "Sage", render: (r) => pretty(r.sage_posting_status) }, { label: "Sage invoice", render: (r) => cut(r.sage_invoice_id) }, { label: "Posted", render: (r) => date(r.sage_posted_at) }];

  return <main className="min-h-screen bg-slate-50 px-6 py-8 text-slate-950"><div className="mx-auto flex max-w-7xl flex-col gap-6">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Link href="/internal" className="text-sm font-semibold text-sky-600">← Back to internal dashboard</Link><p className="mt-6 text-sm font-medium uppercase tracking-[0.2em] text-sky-500">Admin-only VAT Return Workbench</p><div className="mt-3 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight">VAT return control dashboard</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">Read-only workbench with tabs, filters, pagination and draft pack generation. Sage posting remains disabled.</p></div><div className="rounded-2xl bg-slate-100 px-4 py-3 text-sm text-slate-700"><div className="font-medium text-slate-950">{s((staff as Row).full_name) || "Admin"}</div><div>{s((staff as Row).role_type)}</div></div></div></section>
    {vatError ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-900">VAT draft generation failed: {vatError}</div> : null}
    {vatGenerated ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">Draft VAT return run generated: {vatGenerated}</div> : null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Card label="Foundation layer" value={foundationReady ? "Present" : "Missing"} detail={foundationReady ? "Run, line, blocker, journal and match tables visible." : "Apply the VAT foundation migration first."} state={foundationReady ? "ok" : "warn"} /><Card label="Open blockers" value={String(openVatBlockers.count)} detail={vatBlockers.error ?? `${vatBlockers.count} blocker records total.`} state={openVatBlockers.count > 0 ? "warn" : vatBlockers.error ? "block" : "ok"} /><Card label="Return runs" value={String(vatReturnRuns.count)} detail={vatReturnRuns.error ?? `${vatReturnRunLines.count} source-line rows.`} state={vatReturnRuns.error || vatReturnRunLines.error ? "block" : "info"} /><Card label="Adjustment journals" value={String(vatAdjustmentJournals.count)} detail={vatAdjustmentJournals.error ?? `${vatAdjustmentJournalLines.count} journal lines.`} state={vatAdjustmentJournals.error || vatAdjustmentJournalLines.error ? "block" : "info"} /><Card label="Match evidence" value={String(vatMatchEvidence.count)} detail={vatMatchEvidence.error ?? "Sage submitted box evidence records."} state={vatMatchEvidence.error ? "block" : "info"} /><Card label="Sales invoices" value={String(salesInvoices.count)} detail={`${draftSalesInvoices.count} draft, ${postedSalesInvoices.count} posted.`} state={salesInvoices.error ? "block" : "info"} /><Card label="Funding events" value={String(fundingEvents.count)} detail={fundingEvents.error ?? "Box 6 prepayment source spine."} state={fundingEvents.error ? "block" : "info"} /><Card label="Sage coverage" value={String(customerSalesSnapshots.count)} detail={`${postedCustomerSalesSnapshots.count} customer sales posted. ${postedReceiptSnapshots.count} receipts posted/review.`} state={customerSalesSnapshots.error || receiptSnapshots.error ? "block" : "info"} /></section>
    <GenerateDraftRunPanel foundationReady={foundationReady} />
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold tracking-tight">Workflow preview</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Draft generation now creates source-line snapshots only. Journal approval, Sage posting, Sage submission evidence and lock remain future gated steps.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><Step no="1" title="Generate" detail="Draft pack." active /><Step no="2" title="Review" detail="Boxes and blockers." /><Step no="3" title="Approve journals" detail="Calculated only." /><Step no="4" title="Post journals" detail="After approval." /><Step no="5" title="Submit in Sage" detail="Admin submits." /><Step no="6" title="Match and lock" detail="Compare and lock." /></div></section>
    <Tabs active={activeTab} current={current} />
    <FilterBar active={activeTab} current={current} q={q} status={status} severity={severity} pageSize={pageSize} />
    {activeTab === "overview" ? <div className="grid gap-4"><section className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5 text-sm leading-6 text-emerald-900"><h2 className="font-semibold">What matters first</h2><p className="mt-2">Generate a draft pack, check open blockers, review latest run status and journal queue. Source facts sit behind tabs so hundreds of rows do not bury the control decision.</p></div><div className="rounded-3xl border border-sky-200 bg-sky-50 p-5 text-sm leading-6 text-sky-900"><h2 className="font-semibold">Volume handling active</h2><p className="mt-2">Use search, status/severity filters, page size and pagination before opening high-volume tabs.</p></div></section><Table title="VAT blockers" data={blockers} columns={blockerCols} /><Pager active={activeTab} current={current} total={blockers.count} page={page} pageSize={pageSize} /><Table title="VAT return runs" data={runs} columns={runCols} /></div> : null}
    {activeTab === "runs" ? <><Table title="VAT return runs" data={runs} columns={runCols} /><Pager active={activeTab} current={current} total={runs.count} page={page} pageSize={pageSize} /></> : null}
    {activeTab === "blockers" ? <><Table title="VAT blockers" data={blockers} columns={blockerCols} /><Pager active={activeTab} current={current} total={blockers.count} page={page} pageSize={pageSize} /></> : null}
    {activeTab === "journals" ? <><Table title="VAT adjustment journals" data={journals} columns={journalCols} /><Pager active={activeTab} current={current} total={journals.count} page={page} pageSize={pageSize} /></> : null}
    {activeTab === "source" ? <div className="grid gap-4"><Table title="Sales invoices" data={invoices} columns={invoiceCols} /><Pager active={activeTab} current={current} total={invoices.count} page={page} pageSize={pageSize} /><Table title="Funding events" data={funds} columns={fundingCols} /></div> : null}
    {activeTab === "sage" ? <div className="grid gap-4"><Table title="Customer receipt-on-account snapshots" data={receipts} columns={receiptCols} /><Pager active={activeTab} current={current} total={receipts.count} page={page} pageSize={pageSize} /><Table title="Sage customer sales snapshots" data={sageRows} columns={sageCols} /></div> : null}
  </div></main>;
}
