BEGIN;

-- VAT Return Workbench draft generator v1
-- Additive RPC only. Creates a draft run and source-line snapshot.
-- No Sage API call. No journal approval. No journal posting.
-- Controlling contract: docs/governing-pack/ui/VAT_RETURN_WORKBENCH_AND_SAGE_JOURNAL_CONTRACT_v1.md

SET LOCAL lock_timeout = '15s';
SET LOCAL statement_timeout = '0';

CREATE OR REPLACE FUNCTION public.generate_vat_return_draft_run_v1(
  p_period_start_date date,
  p_period_end_date date,
  p_return_period_label text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_staff_id uuid;
  v_auth_user_id uuid := auth.uid();
  v_run_id uuid;
  v_label text;
  v_sales_lines integer := 0;
  v_funding_lines integer := 0;
  v_receipt_lines integer := 0;
  v_sage_sales_lines integer := 0;
  v_blockers integer := 0;
  v_expected_box6 numeric(18,2) := 0;
BEGIN
  IF v_auth_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_period_start_date IS NULL OR p_period_end_date IS NULL THEN
    RAISE EXCEPTION 'VAT period start and end dates are required';
  END IF;

  IF p_period_end_date < p_period_start_date THEN
    RAISE EXCEPTION 'VAT period end date cannot be before start date';
  END IF;

  IF NOT public.internal_has_vat_return_admin_access_v1() THEN
    RAISE EXCEPTION 'Admin-only VAT Return Workbench access required';
  END IF;

  SELECT s.id
  INTO v_staff_id
  FROM public.staff s
  WHERE s.auth_user_id = v_auth_user_id
    AND s.active = true
    AND s.role_type = 'admin'
  LIMIT 1;

  IF v_staff_id IS NULL THEN
    RAISE EXCEPTION 'Admin staff record not found';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.vat_return_runs r
    WHERE r.period_start_date = p_period_start_date
      AND r.period_end_date = p_period_end_date
      AND r.status <> 'matched_to_sage_locked'
  ) THEN
    RAISE EXCEPTION 'An unlocked VAT return run already exists for this period';
  END IF;

  v_label := COALESCE(
    NULLIF(trim(p_return_period_label), ''),
    to_char(p_period_start_date, 'YYYY-MM-DD') || ' to ' || to_char(p_period_end_date, 'YYYY-MM-DD')
  );

  INSERT INTO public.vat_return_runs (
    return_period_label,
    period_start_date,
    period_end_date,
    status,
    generated_by_staff_id,
    generated_by_auth_user_id,
    notes
  ) VALUES (
    v_label,
    p_period_start_date,
    p_period_end_date,
    'draft',
    v_staff_id,
    v_auth_user_id,
    'Draft source-line snapshot generated by generate_vat_return_draft_run_v1. No Sage journals approved or posted.'
  )
  RETURNING id INTO v_run_id;

  WITH source_sales AS (
    SELECT
      si.*,
      COALESCE(si.consideration_received_date, si.sage_invoice_date, si.created_at::date) AS vat_tax_point_date
    FROM public.sales_invoices si
    WHERE COALESCE(si.consideration_received_date, si.sage_invoice_date, si.created_at::date)
      BETWEEN p_period_start_date AND p_period_end_date
  )
  INSERT INTO public.vat_return_run_lines (
    vat_return_run_id,
    line_kind,
    source_table,
    source_id,
    source_ref,
    source_json,
    source_lineage_json,
    box_number,
    direction,
    amount_gbp,
    vat_amount_gbp,
    vat_basis,
    tax_point_date,
    return_period_label,
    natural_sage_covered,
    adjustment_required,
    adjustment_reason,
    status
  )
  SELECT
    v_run_id,
    'sales_invoice_box6_candidate',
    'sales_invoices',
    ss.id,
    COALESCE(ss.invoice_type, 'sales_invoice') || ':' || ss.id::text,
    to_jsonb(ss),
    jsonb_build_object(
      'sales_invoice_id', ss.id,
      'sage_invoice_id', ss.sage_invoice_id,
      'sage_status', ss.sage_status,
      'sage_posted_at', ss.sage_posted_at,
      'zero_rating_deadline_date', ss.zero_rating_deadline_date,
      'zero_rating_status', ss.zero_rating_status
    ),
    6,
    'natural',
    COALESCE(ss.amount_gbp, 0),
    0,
    'sales_invoice_amount_gbp',
    ss.vat_tax_point_date,
    v_label,
    (COALESCE(ss.sage_status, '') = 'posted' OR ss.sage_invoice_id IS NOT NULL),
    NOT (COALESCE(ss.sage_status, '') = 'posted' OR ss.sage_invoice_id IS NOT NULL),
    CASE
      WHEN (COALESCE(ss.sage_status, '') = 'posted' OR ss.sage_invoice_id IS NOT NULL) THEN NULL
      ELSE 'box6_possible_sage_gap_sales_invoice_not_posted'
    END,
    'active'
  FROM source_sales ss;

  GET DIAGNOSTICS v_sales_lines = ROW_COUNT;

  INSERT INTO public.vat_return_run_lines (
    vat_return_run_id,
    line_kind,
    source_table,
    source_id,
    source_ref,
    source_json,
    source_lineage_json,
    box_number,
    direction,
    amount_gbp,
    vat_amount_gbp,
    vat_basis,
    tax_point_date,
    return_period_label,
    natural_sage_covered,
    adjustment_required,
    status
  )
  SELECT
    v_run_id,
    'funding_event_source_fact',
    'order_funding_events',
    fe.id,
    COALESCE(fe.source_ref, fe.event_type || ':' || fe.id::text),
    to_jsonb(fe),
    jsonb_build_object(
      'funding_event_id', fe.id,
      'event_type', fe.event_type,
      'source_entity_type', fe.source_entity_type,
      'source_ref', fe.source_ref
    ),
    NULL,
    'no_box',
    COALESCE(fe.amount_gbp, 0),
    0,
    'funding_event_amount_gbp_source_fact_only',
    fe.created_at::date,
    v_label,
    false,
    false,
    'active'
  FROM public.order_funding_events fe
  WHERE fe.created_at::date BETWEEN p_period_start_date AND p_period_end_date;

  GET DIAGNOSTICS v_funding_lines = ROW_COUNT;

  INSERT INTO public.vat_return_run_lines (
    vat_return_run_id,
    line_kind,
    source_table,
    source_id,
    source_ref,
    source_json,
    source_lineage_json,
    box_number,
    direction,
    amount_gbp,
    vat_amount_gbp,
    vat_basis,
    tax_point_date,
    return_period_label,
    natural_sage_covered,
    adjustment_required,
    status
  )
  SELECT
    v_run_id,
    'sage_customer_receipt_source_fact',
    'cash_posting_snapshots',
    cps.id,
    COALESCE(cps.order_ref, cps.id::text),
    to_jsonb(cps),
    jsonb_build_object(
      'cash_posting_snapshot_id', cps.id,
      'order_ref', cps.order_ref,
      'sage_payment_on_account_id', cps.sage_payment_on_account_id,
      'sage_posting_status', cps.sage_posting_status
    ),
    NULL,
    'no_box',
    COALESCE(cps.amount_gbp, 0),
    0,
    'cash_receipt_source_fact_only',
    COALESCE(cps.posting_date, cps.created_at::date),
    v_label,
    (COALESCE(cps.sage_posting_status, '') IN ('posted', 'posted_needs_review')),
    false,
    'active'
  FROM public.cash_posting_snapshots cps
  WHERE cps.posting_category = 'customer_receipt_on_account'
    AND COALESCE(cps.posting_date, cps.created_at::date) BETWEEN p_period_start_date AND p_period_end_date;

  GET DIAGNOSTICS v_receipt_lines = ROW_COUNT;

  INSERT INTO public.vat_return_run_lines (
    vat_return_run_id,
    line_kind,
    source_table,
    source_id,
    source_ref,
    source_json,
    source_lineage_json,
    box_number,
    direction,
    amount_gbp,
    vat_amount_gbp,
    vat_basis,
    tax_point_date,
    return_period_label,
    natural_sage_covered,
    adjustment_required,
    status
  )
  SELECT
    v_run_id,
    'sage_customer_sales_coverage_source_fact',
    'sage_posting_snapshots',
    sps.id,
    COALESCE(sps.order_ref, sps.sage_invoice_id, sps.id::text),
    to_jsonb(sps),
    jsonb_build_object(
      'sage_posting_snapshot_id', sps.id,
      'document_type', sps.document_type,
      'order_ref', sps.order_ref,
      'sage_invoice_id', sps.sage_invoice_id,
      'sage_posting_status', sps.sage_posting_status,
      'sage_posted_at', sps.sage_posted_at
    ),
    NULL,
    'no_box',
    COALESCE(sps.amount_gbp, 0),
    0,
    'sage_customer_sales_coverage_source_fact_only',
    COALESCE(sps.sage_posted_at::date, sps.created_at::date),
    v_label,
    (COALESCE(sps.sage_posting_status, '') = 'posted'),
    false,
    'active'
  FROM public.sage_posting_snapshots sps
  WHERE sps.document_lane = 'customer_sales'
    AND sps.active = true
    AND COALESCE(sps.sage_posted_at::date, sps.created_at::date) BETWEEN p_period_start_date AND p_period_end_date;

  GET DIAGNOSTICS v_sage_sales_lines = ROW_COUNT;

  SELECT COALESCE(sum(l.amount_gbp), 0)
  INTO v_expected_box6
  FROM public.vat_return_run_lines l
  WHERE l.vat_return_run_id = v_run_id
    AND l.box_number = 6
    AND l.direction IN ('natural', 'increase');

  IF v_sales_lines = 0 AND v_funding_lines > 0 THEN
    INSERT INTO public.vat_return_blockers (
      vat_return_run_id,
      blocker_code,
      severity,
      owner_role,
      message,
      required_action,
      status
    ) VALUES (
      v_run_id,
      'FUNDING_WITHOUT_SALES_INVOICE_SNAPSHOT',
      'warning',
      'admin',
      'Funding events exist in the VAT period but no sales invoice source lines were captured for the same period.',
      'Review whether Box 6 prepayment timing requires a later source-line engine rule for this period.',
      'open'
    );
  END IF;

  IF v_sales_lines = 0 AND v_sage_sales_lines > 0 THEN
    INSERT INTO public.vat_return_blockers (
      vat_return_run_id,
      blocker_code,
      severity,
      owner_role,
      message,
      required_action,
      status
    ) VALUES (
      v_run_id,
      'SAGE_CUSTOMER_SALES_WITHOUT_PLATFORM_SALES_INVOICE_SNAPSHOT',
      'warning',
      'admin',
      'Sage customer sales snapshots exist in the VAT period but no platform sales invoice source lines were captured.',
      'Review the customer sales invoice source path before approving the VAT run.',
      'open'
    );
  END IF;

  IF (v_sales_lines + v_funding_lines + v_receipt_lines + v_sage_sales_lines) = 0 THEN
    INSERT INTO public.vat_return_blockers (
      vat_return_run_id,
      blocker_code,
      severity,
      owner_role,
      message,
      required_action,
      status
    ) VALUES (
      v_run_id,
      'NO_SOURCE_FACTS_CAPTURED_FOR_PERIOD',
      'warning',
      'admin',
      'No VAT source facts were captured for this period by the draft generator.',
      'Confirm the period dates and source objects before progressing.',
      'open'
    );
  END IF;

  SELECT count(*)
  INTO v_blockers
  FROM public.vat_return_blockers b
  WHERE b.vat_return_run_id = v_run_id
    AND b.status = 'open';

  UPDATE public.vat_return_runs r
  SET
    expected_box6_gbp = v_expected_box6,
    expected_box1_gbp = 0,
    expected_box2_gbp = 0,
    expected_box3_gbp = 0,
    expected_box4_gbp = 0,
    expected_box5_gbp = 0,
    expected_box7_gbp = 0,
    expected_box8_gbp = 0,
    expected_box9_gbp = 0,
    source_counts_json = jsonb_build_object(
      'sales_invoice_box6_candidate_lines', v_sales_lines,
      'funding_event_source_fact_lines', v_funding_lines,
      'sage_customer_receipt_source_fact_lines', v_receipt_lines,
      'sage_customer_sales_coverage_source_fact_lines', v_sage_sales_lines
    ),
    blockers_summary_json = jsonb_build_object(
      'open_blockers', v_blockers,
      'generator_version', 'generate_vat_return_draft_run_v1',
      'sage_posting_performed', false,
      'journal_approval_performed', false
    ),
    updated_at = now()
  WHERE r.id = v_run_id;

  RETURN jsonb_build_object(
    'ok', true,
    'vat_return_run_id', v_run_id,
    'return_period_label', v_label,
    'period_start_date', p_period_start_date,
    'period_end_date', p_period_end_date,
    'sales_invoice_box6_candidate_lines', v_sales_lines,
    'funding_event_source_fact_lines', v_funding_lines,
    'sage_customer_receipt_source_fact_lines', v_receipt_lines,
    'sage_customer_sales_coverage_source_fact_lines', v_sage_sales_lines,
    'expected_box6_gbp', v_expected_box6,
    'open_blockers', v_blockers,
    'sage_posting_performed', false,
    'journal_approval_performed', false
  );
END;
$$;

REVOKE ALL ON FUNCTION public.generate_vat_return_draft_run_v1(date, date, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_vat_return_draft_run_v1(date, date, text) TO authenticated;

COMMENT ON FUNCTION public.generate_vat_return_draft_run_v1(date, date, text) IS 'Admin-only draft VAT return run/source-line snapshot generator. No Sage journal approval or posting.';

NOTIFY pgrst, 'reload schema';

COMMIT;
